import { Column, Entity, JoinColumn, JoinTable, ManyToMany, OneToOne, PrimaryGeneratedColumn } from "typeorm";
import { Product } from "./product.entity";
import { Orders } from "./orders.entity";
import { ApiProperty } from "@nestjs/swagger";

@Entity({
    name: 'ORDER_DETAILS'
})
export class OrderDetails {
    @ApiProperty({
        description: 'The id of the order, generated by the database',
    })
    @PrimaryGeneratedColumn('uuid')
    id: string

    @ApiProperty({
        description: 'The price tag of the product',
    })
    @Column({type:'decimal', precision: 10, scale: 2 })
    price: number;

    @ApiProperty({
        description: 'The order',
    })
    @OneToOne(() => Orders, orders => orders.orderDetails)
    @JoinColumn({name: 'orders_id'})
    orders: Orders

    @ApiProperty({
        description: 'The array of products on that order',
    })
    @ManyToMany(() => Product, product => product.orderDetails)
    @JoinTable({
        name: 'ORDERDETAILS_PRODUCTS',
        joinColumn: {
            name: 'orderDetails_id',
            referencedColumnName: 'id'
        },
        inverseJoinColumn: {
            name: 'products_id',
            referencedColumnName: 'id' //Especifica la columna de la entidad 
        }
    })
    products: Product[]
}